### ISSUE TITLE
ofxLua has bad dependencies

### ISSUE THREAD

**Issue by somas95** [d3cod3/Mosaic-Installer#1]
Reporting here since in ofxLua repo issues are not enabled:

the https://github.com/d3cod3/ofxLua/tree/of-0.10.0 branch has a git submodule pointing to a commit that doesn't exist:

https://github.com/danomatika/swig-openframeworks/tree/43824cca91d5f8344b66fecf48bef6ce998b5dc9

This causes compilations to fail

**Comment by d3cod3** [comment]
Thanks for the info! Already fixed, submodule removed, as for Mosaic install is not needed.
