### ISSUE TITLE
Trying go install on debian 10

### ISSUE THREAD

**Issue by yiids** [d3cod3/Mosaic-Installer#2]
Hi,
Im having trouble installing mosaic on debian 10. The installer script doesnt work since it tries to install libpython3.8-dev. Debian 10 is on libpython3.7-dev. 
I tried manually compiling Mosaic, but it also seems to need python3.8. 
Any ideas?

**Comment by d3cod3** [comment]
Hi, the simplest solution is to install the latest python 3.8 from python official downloads page

you can check this: [https://linuxize.com/post/how-to-install-python-3-8-on-debian-10/](https://linuxize.com/post/how-to-install-python-3-8-on-debian-10/) 

or this: [https://www.linuxfordevices.com/tutorials/ubuntu/install-latest-python-debian-ubuntu-source](https://www.linuxfordevices.com/tutorials/ubuntu/install-latest-python-debian-ubuntu-source)

it's pretty straightforward and should solve the problem.

Please, let me know how it goes!

**Comment by yiids** [comment]
Hi,
I tried that, but no luck, still same errors, always a bit confusing to run have multiple version of python, probably I didnt install it right. I upgraded to debian bullseye, that comes with libpython3.8.  Ran into this issue:https://github.com/openframeworks/openFrameworks/issues/5582 but after downgrading to make 4.2.1 I managed to build mosaic without problems.

**Comment by d3cod3** [comment]
Ok, thanks for the information!

I'll downgrade python to 3.7 then, it will be not a problem and there will be no issues on debian 10

thanks again!

**Comment by yiids** [comment]
Hi,
Reopening cause it still depends on python3.8

**Comment by d3cod3** [comment]
Hi, yes, i'm having some issues switching back to python3.7, due to compatibility with other linux flavours, best solution for now is to install in your system python3.8 using the above links.

You can force using debian 11 repos too, adding the apt for bullseye and install python3.8-dev

```bash
apt-get install -t bullseye python3.8-dev
```
