### ISSUE TITLE
Debian bullseye: Unable to locate package libdispatch-dev

### ISSUE THREAD

**Issue by sphaero** [d3cod3/Mosaic-Installer#4]
```
E: Unable to locate package libdispatch-dev
```
This package isn't available in future versions of Debian, I guess?

**Comment by sphaero** [comment]
Ow forgot:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```

**Comment by d3cod3** [comment]
Hi, thanks for the info, i just tested it until debian 10, i will take a look soon and fix it!

thanks again!

**Comment by yiids** [comment]
the libdispatch-dev package is in the deb-multimedia repo, you can find it here: https://deb-multimedia.org/
