### ISSUE TITLE
FHS convention: local libs should be placed in /usr/local/lib

### ISSUE THREAD

**Issue by sphaero** [d3cod3/Mosaic-Installer#5]
Usually on distros all files in /usr/lib are managed by the package managers. Perhaps it's better to follow convention to place it in /usr/local/lib?

https://github.com/d3cod3/Mosaic-Installer/blob/e7e377adfcd0a36ab97f2b89a5ea3829118055f6/mosaic_installer.sh#L402

**Comment by d3cod3** [comment]
Hi again, you're right, i'll change it right away and push the changes.

thanks for the help!
