### ISSUE TITLE
Ubuntu install errors: harfbuzz lib missing

### ISSUE THREAD

**Issue by RKelln** [d3cod3/Mosaic-Installer#8]
Ran into a small snag when using this installer on Ubuntu 22.04, where the harfbuzz lib was missing.

```
apt install libharfbuzz-dev
```
Was able to resolve the issue.

The end of the script also seemed to have an issue:
```
chown: cannot access 'username:username': No such file or directory
chown: cannot access 'username': No such file or directory
```
Where `username` was the correct username.

However Mosaic was able to launch after this.

**Comment by d3cod3** [comment]
Hey, thanks for the feedback!

Can you post how was the solution for the libharfbuzz-dev? so a can modify the script to automatically do it.

about the ```username``` issue, it could be for different reasons, i'll check it

**Comment by RKelln** [comment]
```
apt install libharfbuzz-dev
```
Was all that was needed to fix the issue on Ubuntu.

**Comment by d3cod3** [comment]
Ok, thanks a lot!
